'use client';

import Link from 'next/link';

/**
 * Terms of Service page - Required for App Store submission
 */
export default function TermsPage() {
  const lastUpdated = 'January 18, 2026';

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-lg shadow-md p-8">
        <Link href="/" className="text-primary hover:underline mb-6 inline-block">
          &larr; Back to ChefWise
        </Link>

        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-gray-500 mb-8">Last updated: {lastUpdated}</p>

        <div className="prose prose-gray max-w-none">
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-700 mb-4">
              By accessing or using ChefWise, you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
            <p className="text-gray-700 mb-4">
              ChefWise is an AI-powered cooking assistant that provides personalized recipe
              recommendations, meal planning, pantry management, and nutrition tracking.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">3. User Accounts</h2>
            <p className="text-gray-700 mb-4">
              You are responsible for maintaining the confidentiality of your account credentials
              and for all activities that occur under your account. You must provide accurate
              information when creating an account.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">4. Subscriptions and Payments</h2>
            <p className="text-gray-700 mb-4">
              ChefWise offers both free and premium subscription tiers. Premium subscriptions
              are billed monthly or annually through the App Store or our website. Subscriptions
              auto-renew unless cancelled at least 24 hours before the end of the current period.
            </p>
            <p className="text-gray-700 mb-4">
              Refunds are handled according to Apple App Store or Google Play Store policies
              for in-app purchases, or according to our refund policy for web purchases.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">5. Acceptable Use</h2>
            <p className="text-gray-700 mb-4">You agree not to:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Use the service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the service</li>
              <li>Upload malicious content or files</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Resell or redistribute the service without permission</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">6. AI-Generated Content</h2>
            <p className="text-gray-700 mb-4">
              Recipes, meal plans, and nutritional information are generated by artificial
              intelligence and are provided for informational purposes only. While we strive
              for accuracy, we do not guarantee that AI-generated content is error-free.
            </p>
            <p className="text-gray-700 mb-4">
              <strong>Important:</strong> Always verify ingredients against your known allergies.
              ChefWise is not a substitute for professional medical or nutritional advice.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">7. Disclaimer of Warranties</h2>
            <p className="text-gray-700 mb-4">
              ChefWise is provided &quot;as is&quot; without warranties of any kind. We do not
              warrant that the service will be uninterrupted, error-free, or free of viruses.
              We are not responsible for any adverse reactions to recipes or ingredients.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">8. Limitation of Liability</h2>
            <p className="text-gray-700 mb-4">
              To the maximum extent permitted by law, ChefWise shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages arising from
              your use of the service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">9. Intellectual Property</h2>
            <p className="text-gray-700 mb-4">
              The ChefWise name, logo, and all related content are our intellectual property.
              Recipes you create or save are yours, but we retain rights to aggregated,
              anonymized data for service improvement.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">10. Termination</h2>
            <p className="text-gray-700 mb-4">
              We may terminate or suspend your account at any time for violations of these
              terms. You may delete your account at any time from the Profile settings.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">11. Changes to Terms</h2>
            <p className="text-gray-700 mb-4">
              We may update these terms from time to time. Continued use of the service after
              changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">12. Contact</h2>
            <p className="text-gray-700 mb-4">
              For questions about these Terms of Service, contact us at:
            </p>
            <p className="text-gray-700">
              <strong>Email:</strong> support@chefwise.app
            </p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-gray-200">
          <Link href="/privacy" className="text-primary hover:underline">
            View Privacy Policy
          </Link>
        </div>
      </div>
    </div>
  );
}
